# Generated by Django 4.2 on 2023-07-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=64)),
                ('module', models.CharField(max_length=64)),
                ('semestre', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=32)),
                ('groupe', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=32)),
                ('details', models.CharField(max_length=600, null=True)),
                ('type', models.CharField(max_length=32)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esig_app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=32)),
                ('semestre', models.CharField(max_length=16)),
                ('vollee', models.CharField(max_length=16)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esig_app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.CharField(max_length=3)),
                ('heure_fin', models.CharField(max_length=3)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esig_app.utilisateur')),
            ],
        ),
    ]
