# Generated by Django 4.2 on 2023-08-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esig_app', '0021_alter_absence_date_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esig_app.semestre'),
        ),
    ]
